name:                six
version:             0.1.0.0
github:              "mstruebing/six"
license:             BSD3
author:              "Max Strübing"
maintainer:          "mxstrbng@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstruebing/six#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  six-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - six
    - containers
    - split

tests:
  six-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - six
