name: d01
version: 0.1.0.0
github: "mstruebing/d01"
license: BSD3
author: "Max Strübing"
maintainer: "mxstrbng@gmail.com"
copyright: "MIT"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/mstruebing/d01#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  d01-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - d01

tests:
  d01-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - d01
      - hspec
      - QuickCheck
