[package]
name = "rust"
version = "0.1.0"
authors = ["Max Strübing <max.struebing@farbenmeer.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
